# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foody Cook Book' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foody Cook Book
  #Keyboard Handler
  pod 'IQKeyboardManagerSwift'

  #JSON Parsing
  pod 'SwiftyJSON'

  #Networking
  pod 'Alamofire'

  #progresshUD
  pod 'ProgressHUD'

  target 'Foody Cook BookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Foody Cook BookUITests' do
    # Pods for testing
  end

end
